language: csharp  
sudo: required  
dist: trusty  

dotnet: 1.0.4
mono:
  - 4.6.1
  - 4.8.1
  - 5.0.1

os:  
  - linux

before_install:
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - curl https://packages.microsoft.com/config/ubuntu/14.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list
  - sudo apt-get update
  - sudo apt-get install -y powershell

script:  
  - powershell ./build.ps1 -Release