version: 0.1.0-{build}
image:
  - Visual Studio 2017
  - Ubuntu
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
  - git config --global core.autocrlf true
install:
  - ps: .\.psscripts\install-dotnet.ps1 -SdkVersions "3.1.300"
build: off
build_script:
  - ps: .\build.ps1 -Release -Pack
test: off
artifacts:
  - path: '**\Giraffe.*.nupkg'
    name: Giraffe NuGet packages
nuget:
  account_feed: false
  project_feed: true
deploy:
  provider: NuGet
  api_key:
    secure: KmGt31DHQC3dKFI3ZLCDKd9S5CnH/cV2Rhx3D3J/5b3qSjBh2U+/HOKyOfxJqY2W
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true