version: 0.1.0-alpha003-{build}
configuration:
  - Release
platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
install:
  - ps: (New-Object System.Net.WebClient).DownloadFile('https://go.microsoft.com/fwlink/?linkid=841686', 'dotnet-core-sdk-rc4.exe')
  - ps: Invoke-Command -ScriptBlock { dotnet-core-sdk-rc4.exe /S /v/qn }
build_script:
  - build.cmd
artifacts:
  - path: '**\AspNetCore.Lambda.*.nupkg'
    name: AspNetCore.Lambda
nuget:
  account_feed: false
  project_feed: false
deploy:
  provider: NuGet
  api_key:
    secure: +XDgIu4Tmln7LKedNmQgMFnyKTxxuCKFRK3V5oKEfwZiakPXRd5C7OueEGBL50oh
  skip_symbols: false
  artifact: /.*AspNetCore.Lambda\..*\.nupkg/
  on:
    appveyor_repo_tag: true