version: 0.1.0-{build}
image: Visual Studio 2017 RC
configuration:
  - Release
platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
  - git config --global core.autocrlf true
build: off
build_script:
  - ps: .\appveyor.ps1
test: off
artifacts:
  - path: '**\AspNetCore.Lambda.*.nupkg'
    name: AspNetCore.Lambda
nuget:
  account_feed: false
  project_feed: false
deploy:
  provider: NuGet
  api_key:
    secure: +XDgIu4Tmln7LKedNmQgMFnyKTxxuCKFRK3V5oKEfwZiakPXRd5C7OueEGBL50oh
  skip_symbols: false
  artifact: /.*AspNetCore.Lambda\..*\.nupkg/
  on:
    appveyor_repo_tag: true