version: 0.1.0-alpha003-{build}
configuration:
  - Release
platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
install:
  - ps: (New-Object System.Net.WebClient).DownloadFile('https://download.microsoft.com/download/5/F/E/5FEB7E95-C643-48D5-8329-9D2C63676CE8/dotnet-dev-win-x64.1.0.0-rc4-004771.exe', 'dotnet-core-sdk.exe')
  - ps: dotnet-core-sdk.exe /install /quiet /norestart
build_script:
  - build.cmd
artifacts:
  - path: '**\AspNetCore.Lambda.*.nupkg'
    name: AspNetCore.Lambda
nuget:
  account_feed: false
  project_feed: false
deploy:
  provider: NuGet
  api_key:
    secure: +XDgIu4Tmln7LKedNmQgMFnyKTxxuCKFRK3V5oKEfwZiakPXRd5C7OueEGBL50oh
  skip_symbols: false
  artifact: /.*AspNetCore.Lambda\..*\.nupkg/
  on:
    appveyor_repo_tag: true